[package]
name = "uhd-usrp"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
num = "0.4.1"
num_enum = "0.7.2"
once_cell = "1.19.0"
thiserror = "1.0.56"
uhd-usrp-sys = { path = "../uhd-usrp-sys"}
