[package]
name = "uhd-usrp"
version = "0.1.0"
edition = "2021"

[dependencies]
num-complex = { version = "^0.4", optional = true }
num_enum = "0.7.2"
once_cell = "1.19.0"
thiserror = "1.0.56"
uhd-usrp-sys = { path = "../uhd-usrp-sys" }

[features]
default = ["num"]
num = ["dep:num-complex"]
